name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::jupyter=1.0.0
  - conda-forge::seaborn=0.11.1
  - conda-forge::pandas=1.4.2
  - conda-forge::numpy=1.22.3
  - conda-forge::pip=20.3.3
  - conda-forge::pandas-profiling=3.1.0
  - conda-forge::pyarrow=2.0
  - conda-forge::ipywidgets=7.6.3
  - conda-forge::Jinja2=3.1.1
  - conda-forge::MarkupSafe=2.0.1
  - pip:
      - wandb==0.12.17