name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core=1.3.2
  - matplotlib=3.8.2
  - pandas=2.1.3
  - pip=23.3.1
  - scikit-learn=1.3.2
  - jupyterlab=4.1.3
  - ydata-profiling=4.16.1
  - pydantic=2.10.3
  - scipy=1.11.4
  - ipywidgets=8.1.5
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0