name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.6.2
  - seaborn=0.12.2
  - pandas=1.5.3
  - pip=23.0.1
  - pandas-profiling=3.6.0
  - pyarrow=11.0.0
  - pip:
      - wandb==0.14.0