name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - hydra-core=1.3.2
  - pandas=2.3.2
  - pip=24.3.1
  - scikit-learn=1.7.2
  - jupyterlab=4.4.7
  - ydata-profiling=4.17.0
  - ipywidgets=8.1.7
  - pip:
      - mlflow==3.3.2
      - wandb==0.21.3
