name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.3.3
  - requests=2.24.0
  - scikit-learn=0.24.1
  - pip:
      - mlflow==2.2.2
      - wandb==0.12.17
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
