name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip=24.3.1
  - requests=2.24.0
  - scikit-learn=1.7.2
  - pip:
      - mlflow==3.3.2
      - wandb==0.21.3
      - -e ..
