name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.0.1
  - requests=2.28.2
  - mlflow=2.2.2
  - scikit-learn=1.2.2
  - pip:
      - wandb==0.14.0
      - git+https://github.com/LesterFreamon/build-ml-pipeline-for-short-term-rental-prices.git#egg=wandb-utils&subdirectory=components
