name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pandas=2.3.2
  - pytest=6.2.2
  - scipy=1.5.2
  - pip=24.3.1
  - pip:
      - mlflow==3.3.2
      - wandb==0.21.3
