name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pyyaml
  - hydra-core=1.3.2
  - pandas=2.3.2
  - pip=24.3.1
  - pip:
      - mlflow==3.3.2
      - wandb==0.21.3
