name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=2.2.2
  - pyyaml=6.0
  - hydra-core=1.3.2
  - pip=23.0.1
  - pip:
      - wandb==0.14.0
      - hydra-joblib-launcher==1.2.0