name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::mlflow=2.0.1
  - conda-forge::pyyaml=5.3.1
  - conda-forge::hydra-core=1.0.6
  - conda-forge::pip=20.3.3
  - pip:
      - wandb==0.12.17