name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.17
  - mlflow=1.14.1
  - pyyaml=5.3.1
  - hydra-core=1.0.6
  - pip=20.3.3
  - numpy=1.19.5
  - pip:
      - wandb==0.10.31
      - protobuf==3.20.0