name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - hydra-core=1.3.2
  - matplotlib=3.10.6
  - pandas=2.3.2
  - pip=24.3.1
  - scikit-learn=1.3.2
  - pip:
      - mlflow==3.3.2
      - wandb==0.21.3
