name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.1.4
  - pip=20.3.3
  - scikit-learn=0.24.1
  - matplotlib=3.2.2
  - pillow=8.1.2
  - pip:
      - mlflow==2.2.2
      - wandb==0.12.17
