name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.0
  - pip=24.3.1
  - requests=2.31.0
  - pyarrow=15.0.0
  - pip:
      - mlflow==3.3.2
      - wandb==0.21.3
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
